export const USERINFO_REQUEST_START = 'USERINFO_REQUEST_START'
export const USERINFO_REQUEST_END = 'USERINFO_REQUEST_END'

export const OPEN_LOGIN_MODAL = 'OPEN_LOGIN_MODAL'
export const CLOSE_LOGIN_MODAL = 'CLOSE_LOGIN_MODAL'
export const CHANGE_LOGIN_STRING = 'CHANGE_LOGIN_STRING'
export const CHANGE_PASSWORD_STRING = 'CHANGE_PASSWORD_STRING'
export const LOGIN_REQUEST_START = 'LOGIN_REQUEST_START'
export const LOGIN_REQUEST_END = 'LOGIN_REQUEST_END'
export const LOGOUT = 'LOGOUT'

export const CHANGE_SEARCH_STRING = 'CHANGE_SEARCH_STRING'
export const SEARCH_REQUEST_START = 'SEARCH_REQUEST_START'
export const SEARCH_REQUEST_END = 'SEARCH_REQUEST_END'
export const SELECT_TERM = 'SELECT_TERM'
export const TOGGLE_COMMENT = 'TOGGLE_COMMENT'

export const TRANSLATION_REQUEST_START = 'TRANSLATION_REQUEST_START'
export const TRANSLATION_REQUEST_END = 'TRANSLATION_REQUEST_END'
