export const CHANGE_ROUTE = 'CHANGE_ROUTE'

export const USERINFO_REQUEST_START = 'USERINFO_REQUEST_START'
export const USERINFO_REQUEST_END = 'USERINFO_REQUEST_END'

export const GET_COMMON_DATA_START = 'GET_COMMON_DATA_START'
export const GET_COMMON_DATA_END = 'GET_COMMON_DATA_END'
export const SET_LANGUAGE = 'SET_LANGUAGE'

export const CREATE_NOTIFICATION = 'CREATE_NOTIFICATION'
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION'

export const OPEN_LOGIN_MODAL = 'OPEN_LOGIN_MODAL'
export const CLOSE_LOGIN_MODAL = 'CLOSE_LOGIN_MODAL'
export const CHANGE_LOGIN_STRING = 'CHANGE_LOGIN_STRING'
export const CHANGE_PASSWORD_STRING = 'CHANGE_PASSWORD_STRING'
export const LOGIN_REQUEST_START = 'LOGIN_REQUEST_START'
export const LOGIN_REQUEST_END = 'LOGIN_REQUEST_END'
export const LOGOUT = 'LOGOUT'

export const CHANGE_SEARCH_STRING = 'CHANGE_SEARCH_STRING'
export const SEARCH_REQUEST_START = 'SEARCH_REQUEST_START'
export const SEARCH_REQUEST_END = 'SEARCH_REQUEST_END'
export const SELECT_TERM = 'SELECT_TERM'
export const TOGGLE_COMMENT = 'TOGGLE_COMMENT'

export const TRANSLATION_REQUEST_START = 'TRANSLATION_REQUEST_START'
export const TRANSLATION_REQUEST_END = 'TRANSLATION_REQUEST_END'
export const CHANGE_TRANSLATION_LOCAL = 'CHANGE_TRANSLATION_LOCAL'
export const TRANSLATION_UPDATE_START = 'TRANSLATION_UPDATE_START'
export const TRANSLATION_UPDATE_END = 'TRANSLATION_UPDATE_END'

export const CHANGE_NEW_TERM_WYLIE = 'CHANGE_NEW_TERM_WYLIE'
export const CHANGE_NEW_TERM_SANSKRIT = 'CHANGE_NEW_TERM_SANSKRIT'
export const ADD_TERM_START = 'ADD_TERM_START'
export const ADD_TERM_END = 'ADD_TERM_END'

export const GET_ALL_TRANSLATORS_START = 'GET_ALL_TRANSLATORS_START'
export const GET_ALL_TRANSLATORS_END = 'GET_ALL_TRANSLATORS_END'
export const GET_TRANSLATOR_INFO_START = 'GET_TRANSLATOR_INFO_START'
export const GET_TRANSLATOR_INFO_END = 'GET_TRANSLATOR_INFO_END'

export const GET_ADMIN_USER_DATA_START = 'GET_ADMIN_USER_DATA_START'
export const GET_ADMIN_USER_DATA_END = 'GET_ADMIN_USER_DATA_END'
export const UPDATE_ADMIN_USER_DATA_START = 'UPDATE_ADMIN_USER_DATA_START'
export const UPDATE_ADMIN_USER_DATA_END = 'UPDATE_ADMIN_USER_DATA_END'
export const CHANGE_ADMIN_USER_DATA = 'CHANGE_ADMIN_USER_DATA'

export const SET_ADMIN_USER_ID = 'SET_ADMIN_USER_ID'
export const UPDATE_ADMIN_USER_PASSWORD_START = 'UPDATE_ADMIN_USER_PASSWORD_START'
export const UPDATE_ADMIN_USER_PASSWORD_END = 'UPDATE_ADMIN_USER_PASSWORD_END'
export const CHANGE_ADMIN_USER_PASSWORD = 'CHANGE_ADMIN_USER_PASSWORD'
